wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: gradients/linear\.bias._type
      5: 1
      6:
      - 1
    - 1: gradients/linear\.bias.values
      5: 1
      6:
      - 1
    - 1: gradients/linear\.bias.bins
      5: 1
      6:
      - 1
    - 1: gradients/linear\.weight._type
      5: 1
      6:
      - 1
    - 1: gradients/linear\.weight.values
      5: 1
      6:
      - 1
    - 1: gradients/linear\.weight.bins
      5: 1
      6:
      - 1
    - 1: gradients/lstm\.bias_hh_l0._type
      5: 1
      6:
      - 1
    - 1: gradients/lstm\.bias_hh_l0.values
      5: 1
      6:
      - 1
    - 1: gradients/lstm\.bias_hh_l0.bins
      5: 1
      6:
      - 1
    - 1: gradients/lstm\.weight_hh_l0._type
      5: 1
      6:
      - 1
    - 1: gradients/lstm\.weight_hh_l0.values
      5: 1
      6:
      - 1
    - 1: gradients/lstm\.weight_hh_l0.bins
      5: 1
      6:
      - 1
    - 1: gradients/lstm\.bias_ih_l0._type
      5: 1
      6:
      - 1
    - 1: gradients/lstm\.bias_ih_l0.values
      5: 1
      6:
      - 1
    - 1: gradients/lstm\.bias_ih_l0.bins
      5: 1
      6:
      - 1
    - 1: gradients/lstm\.weight_ih_l0._type
      5: 1
      6:
      - 1
    - 1: gradients/lstm\.weight_ih_l0.values
      5: 1
      6:
      - 1
    - 1: gradients/lstm\.weight_ih_l0.bins
      5: 1
      6:
      - 1
    - 1: train_loss
      5: 1
      6:
      - 1
    - 1: train_loss_true
      5: 1
      6:
      - 1
    - 1: train_mse
      5: 1
      6:
      - 1
    - 1: train_rmse
      5: 1
      6:
      - 1
    - 1: train_mae
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: test_loss
      5: 1
      6:
      - 1
    - 1: test_loss_true
      5: 1
      6:
      - 1
    - 1: test_mse
      5: 1
      6:
      - 1
    - 1: test_rmse
      5: 1
      6:
      - 1
    - 1: test_mae
      5: 1
      6:
      - 1
    python_version: 3.9.5
    start_time: 1680616430.517166
    t:
      1:
      - 1
      - 9
      - 51
      - 55
      - 77
      2:
      - 1
      - 9
      - 51
      - 55
      - 77
      3:
      - 1
      - 2
      - 7
      - 23
      4: 3.9.5
      5: 0.14.0
      8:
      - 5
accelerator:
  desc: null
  value: null
accumulate_grad_batches:
  desc: null
  value: null
amp_backend:
  desc: null
  value: null
amp_level:
  desc: null
  value: null
auto_lr_find:
  desc: null
  value: false
auto_scale_batch_size:
  desc: null
  value: false
auto_select_gpus:
  desc: null
  value: null
batch_size:
  desc: null
  value: 32
benchmark:
  desc: null
  value: null
censor_level:
  desc: null
  value: '1'
censored:
  desc: null
  value: true
check_val_every_n_epoch:
  desc: null
  value: 1
cluster:
  desc: null
  value: WEBSTER
covariates:
  desc: null
  value: false
dataloader:
  desc: null
  value: EVChargersDataset
default_root_dir:
  desc: null
  value: null
detect_anomaly:
  desc: null
  value: false
devices:
  desc: null
  value: null
enable_checkpointing:
  desc: null
  value: true
enable_model_summary:
  desc: null
  value: true
enable_progress_bar:
  desc: null
  value: true
fast_dev_run:
  desc: null
  value: false
feat_max_val:
  desc: null
  value: 1.0
forecast_lead:
  desc: null
  value: 24
gpus:
  desc: null
  value: null
gradient_clip_algorithm:
  desc: null
  value: null
gradient_clip_val:
  desc: null
  value: null
hidden_dim:
  desc: null
  value: 72
inference_mode:
  desc: null
  value: true
input_dim:
  desc: null
  value: 2
ipus:
  desc: null
  value: null
learning_rate:
  desc: null
  value: 0.001
limit_predict_batches:
  desc: null
  value: null
limit_test_batches:
  desc: null
  value: null
limit_train_batches:
  desc: null
  value: null
limit_val_batches:
  desc: null
  value: null
log_every_n_steps:
  desc: null
  value: 50
logger:
  desc: null
  value: true
loss:
  desc: null
  value: CPNLL
loss_fn:
  desc: null
  value: censored_poisson_negative_log_likelihood
max_epochs:
  desc: null
  value: 1
max_steps:
  desc: null
  value: -1
max_time:
  desc: null
  value: null
min_epochs:
  desc: null
  value: null
min_steps:
  desc: null
  value: null
model_name:
  desc: null
  value: LSTM
move_metrics_to_cpu:
  desc: null
  value: false
multiple_stations:
  desc: null
  value: false
multiple_trainloader_mode:
  desc: null
  value: max_size_cycle
num_layers:
  desc: null
  value: 1
num_nodes:
  desc: null
  value: 1
num_processes:
  desc: null
  value: null
num_sanity_val_steps:
  desc: null
  value: 2
output_dim:
  desc: null
  value: 1
overfit_batches:
  desc: null
  value: 0.0
plugins:
  desc: null
  value: null
precision:
  desc: null
  value: 32
profiler:
  desc: null
  value: null
reload_dataloaders_every_n_epochs:
  desc: null
  value: 0
replace_sampler_ddp:
  desc: null
  value: true
resume_from_checkpoint:
  desc: null
  value: null
sequence_length:
  desc: null
  value: 72
strategy:
  desc: null
  value: null
sync_batchnorm:
  desc: null
  value: false
test_end:
  desc: null
  value: '2019-06-02'
tpu_cores:
  desc: null
  value: null
track_grad_norm:
  desc: null
  value: -1
train_end:
  desc: null
  value: '2019-05-01'
train_start:
  desc: null
  value: '2019-01-01'
val_check_interval:
  desc: null
  value: null
weight_decay:
  desc: null
  value: 0.0015
