# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Thesis

on:
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '0 6 * * *'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1
        pip install pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-1.13.0+cu116.html
        pip install torch-geometric-temporal
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test models
      run: |
        python test_models.py
